name: publish-beta

on:
  push:
    branches: [ main ]
    paths:
        - 'Pek.Maui.Base/**'
  workflow_dispatch:

jobs:
  build-publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotNET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.x
          9.x
    - name: Restore
      run: |
        dotnet restore Pek.Maui.Base/Pek.Maui.Base.csproj
    - name: Build
      run: |
        dotnet pack --no-restore --version-suffix $(date "+%Y.%m%d-beta%H%M") -c Release -o out Pek.Maui.Base/Pek.Maui.Base.csproj
    - name: Publish
      run: |
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
